const dailyDeals = [
  {
    id: 1,
    title: "New Lilikoi Margarita",
    description: "High melt cheese, bacon, oak leaf, Onion, Mist & tomato, pickles, mustard and….",
    price: "$45.00",
    rating: 4.6,
    restaurantName: "Sunset Grill & Bar",
    address: "123 Ocean Drive, Honolulu, HI",
    contact_no: "+1 808-555-0123",
    image: "deal-1.svg",
    tags: ["Pizza", "Bar", "Grill"],
    position: [30.2672, -97.7431],
    isHot: true,
  },
  {
    id: 2,
    title: "New Lilikoi Margarita",
    description: "High melt cheese, bacon, oak leaf, Onion, Mist & tomato, pickles, mustard and….",
    price: "$45.00",
    rating: 4.2,
    restaurantName: "Island Flame Kitchen",
    address: "456 Palm Street, Honolulu, HI",
    contact_no: "+1 808-555-0145",
    image: "deal-1.svg",
    tags: ["Pizza", "Bar", "Grill"],
    position: [30.2731, -97.7472],
    isHot: false,
  },
  {
    id: 3,
    title: "New Lilikoi Margarita",
    description: "High melt cheese, bacon, oak leaf, Onion, Mist & tomato, pickles, mustard and….",
    price: "$45.00",
    rating: 4.8,
    restaurantName: "Lilikoi Lounge",
    address: "89 Beachwalk Ave, Waikiki, HI",
    contact_no: "+1 808-555-0189",
    image: "deal-1.svg",
    tags: ["Pizza", "Bar", "Grill"],
    position: [30.2619, -97.7398],
    isHot: true,
  },
  {
    id: 4,
    title: "New Lilikoi Margarita",
    description: "High melt cheese, bacon, oak leaf, Onion, Mist & tomato, pickles, mustard and….",
    price: "$45.00",
    rating: 4.1,
    restaurantName: "The Golden Skillet",
    address: "77 Ala Moana Blvd, Honolulu, HI",
    contact_no: "+1 808-555-0111",
    image: "deal-1.svg",
    tags: ["Pizza", "Bar", "Grill"],
    position: [30.2584, -97.7466],
    isHot: false,
  },
  {
    id: 5,
    title: "New Lilikoi Margarita",
    description: "High melt cheese, bacon, oak leaf, Onion, Mist & tomato, pickles, mustard and….",
    price: "$45.00",
    rating: 4.9,
    restaurantName: "Pacific Ember",
    address: "12 Harbor Road, Honolulu, HI",
    contact_no: "+1 808-555-0199",
    image: "deal-1.svg",
    tags: ["Pizza", "Bar", "Grill"],
    position: [30.2762, -97.7421],
    isHot: true,
  },
  {
    id: 6,
    title: "New Lilikoi Margarita",
    description: "High melt cheese, bacon, oak leaf, Onion, Mist & tomato, pickles, mustard and….",
    price: "$45.00",
    rating: 4.3,
    restaurantName: "Aloha Fire Grill",
    address: "301 King Street, Honolulu, HI",
    contact_no: "+1 808-555-0167",
    image: "deal-1.svg",
    tags: ["Pizza", "Bar", "Grill"],
    position: [30.2705, -97.7512],
    isHot: false,
  },
  {
    id: 7,
    title: "New Lilikoi Margarita",
    description: "High melt cheese, bacon, oak leaf, Onion, Mist & tomato, pickles, mustard and….",
    price: "$45.00",
    rating: 4.0,
    restaurantName: "Urban Tiki Tavern",
    address: "88 Downtown Ave, Honolulu, HI",
    contact_no: "+1 808-555-0134",
    image: "deal-1.svg",
    tags: ["Pizza", "Bar", "Grill"],
    position: [30.2556, -97.7404],
    isHot: true,
  },
  {
    id: 8,
    title: "New Lilikoi Margarita",
    description: "High melt cheese, bacon, oak leaf, Onion, Mist & tomato, pickles, mustard and….",
    price: "$45.00",
    rating: 4.7,
    restaurantName: "Coastal Crave",
    address: "19 Seaside Lane, Honolulu, HI",
    contact_no: "+1 808-555-0176",
    image: "deal-1.svg",
    tags: ["Pizza", "Bar", "Grill"],
    position: [30.2748, -97.7369],
    isHot: false,
  },
  {
    id: 9,
    title: "New Lilikoi Margarita",
    description: "High melt cheese, bacon, oak leaf, Onion, Mist & tomato, pickles, mustard and….",
    price: "$45.00",
    rating: 4.4,
    restaurantName: "Flame & Stone",
    address: "245 Lava Road, Honolulu, HI",
    contact_no: "+1 808-555-0152",
    image: "deal-1.svg",
    tags: ["Pizza", "Bar", "Grill"],
    position: [30.2637, -97.7535],
    isHot: true,
  },
  {
    id: 10,
    title: "New Lilikoi Margarita",
    description: "High melt cheese, bacon, oak leaf, Onion, Mist & tomato, pickles, mustard and….",
    price: "$45.00",
    rating: 4.5,
    restaurantName: "Tropical Hearth",
    address: "67 Coconut Plaza, Honolulu, HI",
    contact_no: "+1 808-555-0180",
    image: "deal-1.svg",
    tags: ["Pizza", "Bar", "Grill"],
    position: [30.2592, -97.7355],
    isHot: false,
  },
  {
    id: 11,
    title: "New Lilikoi Margarita",
    description: "High melt cheese, bacon, oak leaf, Onion, Mist & tomato, pickles, mustard and….",
    price: "$45.00",
    rating: 4.1,
    restaurantName: "Harbor Heat",
    address: "9 Pier Street, Honolulu, HI",
    contact_no: "+1 808-555-0109",
    image: "deal-1.svg",
    tags: ["Pizza", "Bar", "Grill"],
    position: [30.2783, -97.7459],
    isHot: true,
  },
  {
    id: 12,
    title: "New Lilikoi Margarita",
    description: "High melt cheese, bacon, oak leaf, Onion, Mist & tomato, pickles, mustard and….",
    price: "$45.00",
    rating: 4.8,
    restaurantName: "Ember Coast Kitchen",
    address: "410 Sunset Blvd, Honolulu, HI",
    contact_no: "+1 808-555-0190",
    image: "deal-1.svg",
    tags: ["Pizza", "Bar", "Grill"],
    position: [30.2724, -97.7328],
    isHot: false,
  },
];

export default dailyDeals;
